version: '3.9'

services:
  frontend:
    restart: always

    container_name: Front
    env_file:
      - ./Frontend/.env
    build:
      context: ./Frontend
    ports:
      - 8080:8080
    expose:
      - 8080

  backend:
    restart: always
    container_name: backend
    build:
      context: ./
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./Database/DB.env
    command:  uvicorn Application.main:app --host=0.0.0.0 --port=8000
  db:
    image: postgres
    env_file:
      - ./Database/DB.env
    ports:
      - 5432:5432
  bot:
    container_name: tgbot
    build: ./Services/
    depends_on:
      - backend

